# Change the configuration for your use case.
#
# Refer to https://www.aerospike.com/docs/connectors/enterprise/kafka/outbound/configuration/index.html
# for details.

# The connector's listening ports, TLS and network interface.
service:
  port: 8080

# Format of the Kafka destination message.
format:
  mode: flat-json
  metadata-key: metadata

# Aerospike record routing to a Kafka destination.
routing:
  mode: static
  destination: aerospike

# Kafka producer initialization properties.  -> IP : 192.168.1.4 -> this is IP address got from CMD : ifconfig, we cannot use localhost, since in docker image it refer to local machine
producer-props:
  bootstrap.servers:
    - 192.168.1.4:9092

# The logging properties.
logging:
  enable-console-logging: true